### PR TITLE
Updates to run against AR5

### PR DESCRIPTION
**Pull request by jimcavoli**
This one required very little to bring it current; quick update to dependencies and it's ready to rock. I made these changes according to the way the other gems have been updated, freshened everything with `schema_dev`, and got passing tests.

Technically, due to the way these changes were done, this gem could specify broader dependencies to allow the older versions of AR and `schema_plus_core` to update with a version bump less than major, but I figured that was best decided by the project at large. I'm happy to make those changes as well if desired.

### CODE REVIEW

**Comment by boazy** [comment]
Thanks @jimcavoli.
Can you please specify a broader scope? This is what we did with other gems which could easily support both versions of ActiveRecord.

**Comment by jimcavoli** [comment]
@boazy Done; tested against rubies 2.2.5 and 2.3.1 as well...even if I mis-spec'd that the first pass on CI 😄

**Comment by boazy** [comment]
@jimcavoli
Sorry for the delay. Thanks for the pull request!

**Comment by boazy** [comment]
@ronen 
Everything passes the tests so you can release a new gem version.

**Comment by ronen** [comment]
Thanks both of you for taking care of this.  I've released this as v0.1.5

Cheers

**Pull request merged**
